### ISSUE TITLE
how to create tab groups in init file?

### ISSUE THREAD

**Issue by titaniumbones** [fritzgrabo/tab-bar-groups#1]
Hi, I'm just starting to use this package and wondering how to create tab groups on startup. So for instnace, I have a bunch of tabs named

DH
HIS
WDW
TUTORIALS

How do I create a tab group on startup and add them all to the group?  Thanks!

**Comment by fritzgrabo** [comment]
Hi Matt!

Thanks for reaching out, I'm glad to hear you're giving my package a spin.

To save a particular set of tab groups (and a bunch of other details regarding your currently session) restored at startup, have a look at [Saving Emacs Sessions](https://www.gnu.org/software/emacs/manual/html_node/emacs/Saving-Emacs-Sessions.html) in the Emacs Manual.

In a gist, start up Emacs and create the tabs and tab groups you'd like to restore later, and run `M-x desktop-save`. It'll ask for a directory, then create an `.emacs.desktop` file in it that describes your current Emacs session. For my example, I had Emacs store the file in the `~/.emacs.d` directory. Then, in your Emacs initialization file, append the following to restore the previously saved tabs and tab groups on startup:

```lisp
(desktop-read "~/.emacs.d")
```
